bs-hl-color={color3}
clock
color=6272A4
daemonize
datestr=%a, %B %e
effect-blur=13x13
effect-vignette=0.5:0.5
fade-in=0.400000
font=Inter
grace=2
grace-no-mouse
grace-no-touch
ignore-empty-password
indicator
indicator-radius=200
indicator-thickness=20
inside-clear-color={background}
inside-color={background}
inside-ver-color={background}
inside-wrong-color={background}
key-hl-color={color2}
line-clear-color={color3}
line-color={background}
line-ver-color={color1}
line-wrong-color={background}
ring-clear-color={color3}
ring-color={color1}
ring-ver-color={color1}
ring-wrong-color=FF5555
screenshot
separator-color=00000000
show-failed-attempts
text-caps-lock-color=
text-clear-color={color3}
text-color=F8F8F2
text-ver-color={color3}
text-wrong-color=FF5555
timestr=%I:%M %p
